add attempts for input host

diff --git a/connect-to-rdp b/connect-to-rdp
--- a/connect-to-rdp
+++ b/connect-to-rdp
@@ -18,9 +18,8 @@ validate_host() {
 
   if ! timeout 3 bash -c "cat < /dev/null > /dev/tcp/$host/3389" 2>/dev/null; then
     echo "Warning! Host - $host is not reachable on port 3389" >&2
-    read -rp "Continue connecting? (y/N) " -n 1 confirm
     echo
-    [[ "$confirm" =~ ^[yY]$ ]] || return 1
+    return 1
   fi
 
   return 0
@@ -45,25 +44,34 @@ main() {
     esac
   done
 
+  local attempts=3
+  # host="${host:-workIp}"
+  if [[ -z "${host:-}" ]]; then
+
+    while ((attempts-- > 0)); do
+      read -rp "Host > " host
+
+      if validate_host "$host"; then
+        echo
+        break
+      fi
+
+      echo -e "Error validate host\n"
+
+    done
+  fi
+
+  ((attempts == 0)) || {
+    echo "Max attempts reached"
+    return 1
+  }
+
   if [[ -z "${user:-}" ]]; then
     read -rp "User > " user
   fi
 
   if [[ -z "${password:-}" ]]; then
     read -rsp "Password > " password
-    echo
-  fi
-
-  # If u wont use default ip uncoment
-  # host="${host:-workIp}"
-  if [[ -z "${host:-}" ]]; then
-    read -rp "Host > " host
-
-    if ! validate_host "$host"; then
-      echo -e "Error validate host\n"
-      exit 1
-    fi
-
     echo
   fi
 
